"""empty message

Revision ID: a32f90ae103c
Revises: 
Create Date: 2018-03-06 14:48:26.478719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32f90ae103c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merch',
    sa.Column('merch_id', sa.Integer(), nullable=False),
    sa.Column('merch_name', sa.String(), nullable=False),
    sa.Column('merch_cost', sa.Float(), nullable=False),
    sa.Column('merch_descr', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('merch_id'),
    sa.UniqueConstraint('merch_name')
    )
    op.create_table('shows',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('show_date', sa.Date(), nullable=False),
    sa.Column('show_venue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('show_id')
    )
    op.create_table('sales',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('merch_name', sa.String(), nullable=False),
    sa.Column('num_sold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merch_name'], ['merch.merch_name'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.show_id'], ),
    sa.PrimaryKeyConstraint('sale_id'),
    sa.UniqueConstraint('show_id', 'merch_name', name='unique_show_merch')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('shows')
    op.drop_table('merch')
    # ### end Alembic commands ###
